const USER_INFO = 'USER_INFO';
const USER_EXPENSES = 'USER_EXPENSES';
const SAVE_CURRENCYS = 'SAVE_CURRENCYS';
const SAVE_EXCHANGE = 'SAVE_EXCHANGE';
const DELETE_EXPENSE = 'DELETE_EXPENSE';
const CHANGE_EXPENSE = 'CHANGE_EXPENSE';
const EDIT_EXPENSE = 'EDIT_EXPENSE';
export {
  USER_INFO,
  USER_EXPENSES,
  SAVE_CURRENCYS,
  SAVE_EXCHANGE,
  DELETE_EXPENSE,
  CHANGE_EXPENSE,
  EDIT_EXPENSE,
};
